name: App build/deploy

on:
  push:
    branches: ['main']
    paths:
      - .github/workflows/publish-app.yml
      - toy-robot/**
  pull_request:
    branches: ['main']

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd toy-robot && npm install

      - name: Build app
        run: cd toy-robot && npm run build
      
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          SOURCE_DIR: toy-robot/dist/
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      # Invalidate Cloudfront Cache, so that the latest changes are reflected
      - name: Cloudfront cache invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'ap-southeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
